### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by joserf** [lazuardyk/Remote-PC-Telegram#2]
Traceback (most recent call last):
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python35\lib\tkinter\__init__.py", line 1549, in __call__
    return self.func(*args)
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python35\lib\tkinter\__init__.py", line 596, in callit
    func(*args)
  File "main.py", line 125, in main
    if update['message']['from']['username'] == owner:
KeyError: 'username'

Any idea what it might be?

**Comment by lazuardyk** [comment]
you must be wrong about your token or your username.
be sure to fill token correctly, and username in the setup is your username's main account not your username's bot.
or try to create new bot from BotFather

**Comment by joserf** [comment]
Tks
